### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by Luis2088** [ardianumam/PartDistill#2]
Thanks for the great work !!!  However, **the [link ](https://drive.google.com/drive/folders/1kzugzkn_9dO-37GcnaQm2qmt4MO7Fw-B) for shapnet data preparation is broken.**  Could you please upload it again? Thank you so much.

**Comment by ardianumam** [comment]
Hi,
The link is resolved. You may check it.

**Comment by Luis2088** [comment]
Hello, I downloaded it.  But I found only **Chair**, can you upload the other categories?


-- shapenet_preprocessed_partdistill
---- 03624134
---- 03001627
The document is structured as above.
